# .github/workflows/release.yml
name: Terraform Provider Release

on:
  push:
    branches:
      - main

jobs:
  terraform-provider-zuora:
    name: Release terraform-provider-zuora
    uses: hashicorp/ghaction-terraform-provider-release/.github/workflows/community.yml@v4
    with:
      setup-go-version-file: 'go.mod'
    secrets:
      gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
