name: Build & Release Terraform Provider

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Build and zip provider binaries
        run: |
          mkdir -p dist
          VERSION=${GITHUB_REF#refs/tags/}
          for OS_ARCH in darwin_amd64 darwin_arm64 linux_amd64 linux_arm64; do
            OS=${OS_ARCH%_*}
            ARCH=${OS_ARCH#*_}
            BIN=terraform-provider-zuora
            OUT=dist/terraform-provider-zuora_${VERSION}_${OS}_${ARCH}.zip

            echo "Building $BIN for $OS/$ARCH"
            GOOS=$OS GOARCH=$ARCH go build -o $BIN

            echo "Zipping into $OUT"
            zip -j $OUT $BIN

            rm $BIN
          done

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: terraform-provider-zuora ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist
          asset_name: |
            terraform-provider-zuora_${{ github.ref_name }}_darwin_amd64.zip
            terraform-provider-zuora_${{ github.ref_name }}_darwin_arm64.zip
            terraform-provider-zuora_${{ github.ref_name }}_linux_amd64.zip
            terraform-provider-zuora_${{ github.ref_name }}_linux_arm64.zip
          asset_content_type: application/zip
