name: Tag on Main Merge

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch all tags
        run: git fetch --tags

      - name: Get latest version
        id: get_version
        run: |
          latest_tag=$(git tag -l 'v*' --sort=-v:refname | head -n 1)
          if [[ $latest_tag == v* ]]; then
            version=${latest_tag#v}
            IFS='.' read -r major minor patch <<< "$version"
            patch=$((patch + 1))
            new_tag="v$major.$minor.$patch"
          else
            new_tag="v0.1.0"
          fi
          echo "new_tag=$new_tag" >> "$GITHUB_OUTPUT"

      - name: Create new tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ steps.get_version.outputs.new_tag }}
          git push origin ${{ steps.get_version.outputs.new_tag }}
